# Generated by Django 3.2.7 on 2021-10-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='centre',
            name='emplacement',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='centre',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='centre',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='emplacement',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
