# Generated by Django 3.2.8 on 2021-10-14 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0003_auto_20211003_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='centre',
            name='type',
            field=models.CharField(choices=[('Hopital', 'Hopital'), ('Equipe mobile', 'Equipe mobile'), ('District sanitaire', 'District sanitaire')], default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='fonction',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='place_birth',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
