# Generated by Django 3.2.7 on 2021-10-03 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vac', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_adds', to=settings.AUTH_USER_MODEL),
        ),
    ]
