# Generated by Django 3.2.8 on 2021-10-14 08:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vac', '0002_patient_agent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaccin',
            old_name='lot',
            new_name='nlot',
        ),
        migrations.RemoveField(
            model_name='vaccin',
            name='description',
        ),
        migrations.AddField(
            model_name='patient',
            name='code',
            field=models.CharField(default='', max_length=15, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='commune',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='enfants',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='matrimoniale',
            field=models.CharField(choices=[('Marie', 'Marie'), ('Celibataire', 'Celibataire'), ('En couple', 'En_couple')], default='Marie', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='nationality',
            field=models.CharField(default='CI', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='pays',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='image_patients/'),
        ),
        migrations.AddField(
            model_name='patient',
            name='place_birth',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='profession',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='sexe',
            field=models.CharField(choices=[('M', 'Homme'), ('F', 'Femme')], default='H', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='ville',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vaccin',
            name='exp',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vaccin',
            name='quantite',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vaccin',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='TestSero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetest', models.DateField()),
                ('igg', models.IntegerField()),
                ('igm', models.IntegerField()),
                ('laboratoire', models.CharField(max_length=150)),
                ('dateajout', models.DateField()),
                ('fichier', models.FileField(blank=True, null=True, upload_to='testsero/')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vac.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Enquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poids', models.FloatField()),
                ('taille', models.FloatField()),
                ('created_at', models.DateTimeField()),
                ('temp', models.FloatField()),
                ('positifcov', models.BooleanField(default=False)),
                ('datepositive', models.DateField(blank=True, null=True)),
                ('maladies', models.TextField(default='')),
                ('vaccine', models.BooleanField(default=False)),
                ('signeclinique', models.TextField(default='')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vac.patient')),
                ('testsero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vac.testsero')),
            ],
        ),
    ]
